"""added w.requests

Revision ID: 185c20d0af28
Revises: 
Create Date: 2026-04-20 07:00:01.373901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185c20d0af28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requests', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('widget', schema=None) as batch_op:
        batch_op.drop_column('requests')

    # ### end Alembic commands ###
